name: cloudMusic_flutter
description: "flutter 仿网易云音乐"
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  banner: ^0.1.3
  flutter_redux: ^0.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
